// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/service/gofemart.go

// Package service is a generated GoMock package.
package service

import (
	models "go-musthave-diploma-tpl/internal/gophermart/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGofemartRepo is a mock of GofemartRepo interface.
type MockGofemartRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGofemartRepoMockRecorder
}

// MockGofemartRepoMockRecorder is the mock recorder for MockGofemartRepo.
type MockGofemartRepoMockRecorder struct {
	mock *MockGofemartRepo
}

// NewMockGofemartRepo creates a new mock instance.
func NewMockGofemartRepo(ctrl *gomock.Controller) *MockGofemartRepo {
	mock := &MockGofemartRepo{ctrl: ctrl}
	mock.recorder = &MockGofemartRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGofemartRepo) EXPECT() *MockGofemartRepoMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockGofemartRepo) CreateUser(login, password string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", login, password)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockGofemartRepoMockRecorder) CreateUser(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockGofemartRepo)(nil).CreateUser), login, password)
}

// GetUserByID mocks base method.
func (m *MockGofemartRepo) GetUserByID(id int) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockGofemartRepoMockRecorder) GetUserByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockGofemartRepo)(nil).GetUserByID), id)
}

// GetUserByLoginAndPassword mocks base method.
func (m *MockGofemartRepo) GetUserByLoginAndPassword(login, password string) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLoginAndPassword", login, password)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLoginAndPassword indicates an expected call of GetUserByLoginAndPassword.
func (mr *MockGofemartRepoMockRecorder) GetUserByLoginAndPassword(login, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLoginAndPassword", reflect.TypeOf((*MockGofemartRepo)(nil).GetUserByLoginAndPassword), login, password)
}
